config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'requisicaoresposta' => "foodgame#requisicaoresposta"
  resources :logerros
  root "principal#index"
  resources :perguntas
  resources :usuarios
  resources :principal
  get 'inserirpergunta' => "perguntas#new"
end

app/controllers/perguntas_controller.rb
class PerguntasController < ApplicationController
  before_action :authenticate_user!
    def index
        @perguntas = Perguntum.all
    end    

    def new
      @pergunta = Perguntum.new
    end 

    def create
        @pergunta = Perguntum.new(pergunta_params)
  
      if @pergunta.save
        redirect_to "/perguntas", success: "Pergunta inserida com sucesso!"
      else
        redirect_to "/perguntas", danger: "Falha ao inserir pergunta!"
      end
    end    

    def destroy 
        @pergunta = Perguntum.find(params[:id])
        @pergunta.destroy
         redirect_to "/perguntas", success: 'Pergunta deletada com sucesso.' 
    end 

    private
    def pergunta_params
      params.require(:perguntum).permit(:pergunta, :dica, :alternativa_correta, :alternativa_2, :alternativa_3, :alternativa_4, :nivel, :explicacao)
    end
end

app/views/perguntas/index.html.erb
         <%= render 'layouts/sidebar' %>
        <div class="minhamain">
            <div class="alert alert-success">
                <i class="fa fa-eye fa-lg"></i><strong> Perguntas</strong>
                <a class="btn icon-btn btn-outline-success btn-sm pull-right" href="/inserirpergunta">
                    <span class="fa fa-plus"></span>
                    Adicionar Pergunta
                </a>
            </div>
            <div class="row botao">
                <div class="col-md-3">
                    <div class="card p-30 card-fluid" style="background-color: #f2f3f5;">
                        <div class="media">
                            <div class="media-left meida media-middle" style="margin: auto; margin-top: 10px; margin-left: 10%; margin-right: 10%;">
                                <span><i class="fa fa-question-circle fa-3x text-primary f-s-40 color-primary"></i></span>
                            </div>
                            <div class="media-body media-text-right" style="margin: auto; margin-top:10px;">
                                <h2 class="text-primary">32</h2>
                                <p class="m-b-0" style="color: #4f5b69; font-size: 65%;">Fáceis</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card p-30" style="background-color: #f2f3f5;">
                        <div class="media">
                            <div class="media-left meida media-middle" style="margin: auto; margin-top: 10px; margin-left: 10%; margin-right: 10%;">
                                <span><i class="fa fa-question-circle fa-3x f-s-40 color-success text-success"></i></span>
                            </div>
                            <div class="media-body media-text-right" style="margin: auto; margin-top:10px;">
                                <h2 class="text-success">21</h2>
                                <p class="m-b-0" style="color: #4f5b69; font-size: 65%;">Médias</p>
                            </div>
                        </div>
                    </div>
                </div>
                                        <div class="col-md-3">
                    <div class="card p-30" style="background-color: #f2f3f5;">
                        <div class="media">
                            <div class="media-left meida media-middle" style="margin: auto; margin-top: 10px; margin-left: 10%; margin-right: 10%;">
                                <span><i class="fa fa-question-circle fa-3x f-s-40 color-warning text-warning"></i></span>
                            </div>
                            <div class="media-body media-text-right" style="margin: auto; margin-top:10px;">
                                <h2 class="text-warning">32</h2>
                                <p class="m-b-0" style="color: #4f5b69; font-size: 65%;">Difíceis</p>
                            </div>
                        </div>
                    </div>
                </div>
                                        <div class="col-md-3">
                    <div class="card p-30" style="background-color: #f2f3f5;">
                        <div class="media">
                            <div class="media-left meida media-middle" style="margin: auto; margin-top: 10px; margin-left: 10%; margin-right: 10%;">
                                <span><i class="fa fa-question-circle fa-3x f-s-40 color-danger text-danger"></i></span>
                            </div>
                            <div class="media-body media-text-right" style="margin: auto; margin-top:10px;">
                                <h2 class="text-danger">34</h2>
                                <p class="m-b-0" style="color: #4f5b69; font-size: 65%;">Muito Dificeis</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group col-lg-6 col-xs-4 container">  
                <select class="filters-select form-control" style="margin-bottom: 10px;margin-top: 10px; display: inline-block;background-color:#fafafa">
                    <option class="btn btn-outline-success  menu-header" value="*">Mostrar Tudo</option>  
                    <option class="btn btn-outline-success  menu-header" value=".facil"/> Perguntas Fáceis</option>
                    <option class="btn btn-outline-success  menu-header" value=".medio"/> Perguntas Médias</option>
                    <option class="btn btn-outline-success  menu-header" value=".dificil"/> Perguntas Dificeis</option>
                    <option class="btn btn-outline-success  menu-header" value=".muito_dificil"/> Perguntas Muito Dificeis</option>
                </select>                
            </div>
            <table id="container">
                <!-- percorre contatos montando as linhas da tabela -->
                <% @perguntas.each do |pergunta| %>
                    <div class="grid">
                        <ul class="container-fluid col-lg-12 element-item <%= pergunta.nivel %>">
                            <dl class="list-group-item"><h3>Pergunta: </h3><h2><%= pergunta.pergunta %></h2></dl>
                            <dl class="list-group-item"><h3>Nivel: </h3> <h2><%= pergunta.nivel %></h2></dl>
                            <dl class="list-group-item"><h3>Alternativa Correta: </h3> <h2><%= pergunta.alternativa_correta %></h2></dl>
                            <dl class="list-group-item"><h3>Alternativa 2: </h3> <h2><%= pergunta.alternativa_2 %></h2></dl>
                            <dl class="list-group-item"><h3>Alternativa 3: </h3> <h2><%= pergunta.alternativa_3 %></h2></dl>
                            <dl class="list-group-item"><h3>Alternativa 4: </h3> <h2><%= pergunta.alternativa_4 %></h2></dl>
                            <dl class="list-group-item"><h3>Explicação: </h3> <h2><%= pergunta.explicacao %></h2></dl>
                            <dl class="list-group-item"><h3>Dica: </h3> <h2><%= pergunta.dica %></h2></dl>
                            <dl class="list-group-item">
                            <%= button_to pergunta_path(pergunta), method: :delete, remote: true, class: "btn btn-outline-danger" do %>
                                 <span class="fa fa-trash-o"></span> Excluir
                            <% end %>

                            </dl>
                        </ul>
                    </div>             
                <% end %>
            </table>
        </div>
       

app/views/perguntas/new.html.erb
 <%= render 'layouts/sidebar' %>
 <div class="minhamain">
            <div class="alert alert-success">
                <strong> <i class="fa fa-plus fa-lg"></i> Adicione uma Pergunta</strong>  
            </div>
            <div class="container col-lg-6">
    <%= form_for @pergunta, url: {action: "create"} do |f| %>
	
    <% if @pergunta.errors.any? %>
	<div id="errors">
	      <h2><%= pluralize(@pergunta.errors.count, "error") %> prevented this post from saving:</h2>
		  <ul>
		      <% @post.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
		  <% end %>

		  </ul>
	</div>
	<% end %>

	<%= f.text_area :pergunta,  class:'form-control', placeholder: 'Digite a Pergunta', size: "60x4" %><br>
	
	<%= f.text_area :dica, class:'form-control', placeholder: 'Insira a Dica', size: "60x2" %><br>
    
	<%= f.text_field :alternativa_correta, class:'form-control', placeholder: 'Alternativa Correta' %><br>
	
	<%= f.text_field :alternativa_2, class:'form-control', placeholder: 'Alternativa 2' %><br>
	
	<%= f.text_field :alternativa_3, class:'form-control',  placeholder: 'Alternativa 3' %><br>
	
	<%= f.text_field :alternativa_4, class:'form-control',  placeholder: 'Alternativa 4' %><br>
	
    <%= f.text_field :nivel, class:'form-control',  placeholder: 'Nível' %><br>

	<%= f.text_area :explicacao, class:'form-control',  placeholder: 'Explicação', size: "60x4" %><br>
	
	<%= f.submit "Adicionar Pergunta", class: "btn btn-success btn-block rounded mx-auto d-block" %>
        <br>
<% end %>
            </div>
        </div>