config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'requisicaoresposta' => "foodgame#requisicaoresposta"
  resources :logerros
  root "principal#index"
  resources :perguntas
  resources :usuarios
  resources :principal
  get 'inserirpergunta' => "perguntas#new"
end

app/controllers/logerros_controller.rb
class LogerrosController < ApplicationController
    before_action :authenticate_user!
    def index
        @logerros = Erro.all
    end    

    def destroy 
        @erro = Erro.find(params[:id])
        @erro.destroy
         redirect_to "/logerros", success: 'Erro deletado com sucesso.' 
    end    
end

app/views/logerros/index.html.erb
        <%= render 'layouts/sidebar' %>
        <div class="minhamain">
            <div class="alert alert-success" onclick="teste()">
                <i class="fa fa-eye fa-lg"></i><strong> Veja os Erros</strong> 
            </div>
             <table id="container">
                <!-- percorre contatos montando as linhas da tabela -->
                <% @logerros.each do |erro| %>
                    <div class="grid">
                        <ul class="container-fluid col-lg-11 element-item ${erro.id}">
                            <dl class="list-group-item"><h3>Usuario: </h3><h2><%= erro.usuario %></h2></dl>
                            <dl class="list-group-item"><h3>Data: </h3><h2><%= erro.data %></h2></dl>
                            <dl class="list-group-item"><h3>Versão: </h3> <h2><%= erro.versaoAndroid %></h2></dl>
                            <dl class="list-group-item"><h3>Fabricante: </h3> <h2><%= erro.fabricante %></h2></dl>
                            <dl class="list-group-item"><h3>Modelo: </h3> <h2><%= erro.modelo %></h2></dl>
                            <dl class="list-group-item"><h3>StackTrace: </h3> <h2><%= erro.stackTrace %></h2></dl>
                            <dl class="list-group-item">
                               <%= button_to logerro_path(erro), method: :delete, remote: true, class: "btn btn-outline-danger" do %>
                                 <span class="fa fa-trash-o"></span> Excluir
                            <% end %> 
                            </dl>
                        </ul>
                    </div>             
                <% end %>
            </table>